### ISSUE TITLE
NoSuchMethodError exception thrown

### ISSUE THREAD

**Issue by Tofpu** [Revxrsal/Lamp#14]
Hi! first, of all, I'd like to thank you for creating this framework, it's incredibly useful to me & (pretty sure) others!

Back to the point, the NoSuchMethodError exception is being thrown when attempting to access the player's locale (`Player#getLocale`) on 1.8.8. Such a method doesn't exist on 1.8.8 unfortunately.

 ```
 java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.entity.Player.getLocale()'

[02:10:10 WARN]:        at revxrsal.commands.bukkit.core.BukkitActor.getLocale(BukkitActor.java:90)

[02:10:10 WARN]:        at revxrsal.commands.command.CommandActor.errorLocalized(CommandActor.java:106)

[02:10:10 WARN]:        at revxrsal.commands.exception.DefaultExceptionHandler.missingArgument(DefaultExceptionHandler.java:25)
 ```
 
 You can avoid the exception by adding a check that ensures that the server version is on a certain version (1.12.2 & higher) before attempting to execute the method.

**Comment by Revxrsal** [comment]
Fixed in 3.0.1. Thank you for reporting!
