### ISSUE TITLE
Command Suggestion Error

### ISSUE THREAD

**Issue by TehNeon** [Revxrsal/Lamp#2]
As of v1.4 there appears to be an issue with parent commands with suggesting subcommands out of the gate. With the example code the when getting suggestions to prompt when inputting "/testcommand " the error will occur. As soon as there is further input, i.e "/testcommand sub", suggestions will be provided.

Example command:
```
import org.bukkit.command.CommandSender
import revxrsal.commands.annotation.Command
import revxrsal.commands.annotation.Subcommand

@Command("testcommand")
class TestCommand
{

	@Subcommand("subcommand1")
	fun subCommand1(sender: CommandSender)
	{
		sender.sendMessage("1")
	}

	@Subcommand("subcommand2")
	fun subCommand2(sender: CommandSender)
	{
		sender.sendMessage("2")
	}

}
```

Error log:
```
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/testcommand ' in plugin LampTest v1.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[patched_1.17.1.jar:git-Paper-302]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.17.1.jar:git-Paper-302]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.17.1.jar:git-Paper-302]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.tabCompleteCommand(CraftServer.java:2136) ~[patched_1.17.1.jar:git-Paper-302]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.tabComplete(CraftServer.java:2108) ~[patched_1.17.1.jar:git-Paper-302]
	at org.bukkit.craftbukkit.v1_17_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.17.1.jar:git-Paper-302]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.17.1.jar:git-Paper-302]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:598) ~[patched_1.17.1.jar:git-Paper-302]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:580) ~[patched_1.17.1.jar:git-Paper-302]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:819) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-302]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-302]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-302]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-302]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-302]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-302]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-302]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-302]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.IllegalStateException: Path cannot be empty!
	at revxrsal.commands.util.Preconditions.notEmpty(Preconditions.java:17) ~[LampTest.jar:?]
	at revxrsal.commands.core.CommandPath.get(CommandPath.java:40) ~[LampTest.jar:?]
	at revxrsal.commands.core.BaseAutoCompleter.complete(BaseAutoCompleter.java:76) ~[LampTest.jar:?]
	at revxrsal.commands.bukkit.core.BukkitCommandExecutor.onTabComplete(BukkitCommandExecutor.java:41) ~[LampTest.jar:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[patched_1.17.1.jar:git-Paper-302]
	... 22 more
```

**Comment by TehNeon** [comment]
Closing as I failed to realize 1.5 was released with a fix for this issue.
