### ISSUE TITLE
[3.1.0] java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by HappyAreaBean** [Revxrsal/Lamp#34]
### Details:
* **Lamp**: 3.1.0
* **Minecraft Server Version**: 1.8.8
* Java 17

### Error:
```java
[13:53:15 WARN]: java.lang.IncompatibleClassChangeError: Class com.google.common.base.Suppliers$MemoizingSupplier does not implement the requested interface java.util.function.Supplier
[13:53:15 WARN]: 	at revxrsal.commands.bukkit.core.BukkitActor.getLocale(BukkitActor.java:119)
[13:53:15 WARN]: 	at revxrsal.commands.command.CommandActor.errorLocalized(CommandActor.java:106)
[13:53:15 WARN]: 	at revxrsal.commands.exception.DefaultExceptionHandler.commandInvocation(DefaultExceptionHandler.java:60)
```

### Notes:
I tested with 1.19 and the exception handle worked fine, The stacktrace is printed in the console instead of the error above.
It didn't happen in 3.0.71, Maybe it has something related to Gson version?

**Comment by Revxrsal** [comment]
Should be fixed in https://github.com/Revxrsal/Lamp/commit/89ccf4bc52a223f00f0eccdf0600588344ed12f6.
