### ISSUE TITLE
Buffer overrun error

### ISSUE THREAD

**Issue by JasperTheMinecraftDev** [Revxrsal/Lamp#81]
Hey, I've encountered another error:
```
[11:40:46 INFO]: JasperTheDev issued server command: /cmd
[11:41:12 INFO]: [Not Secure] <JasperTheDev> test
[11:41:15 INFO]: JasperTheDev issued server command: /cmd\
[11:41:15 ERROR]: Could not pass event UnknownCommandEvent to ExamplePlugin v1.0-SNAPSHOT
revxrsal.commands.exception.ArgumentParseException: Buffer overrun while parsing args
	at revxrsal.commands.util.QuotedStringTokenizer$TokenizerState.createException(QuotedStringTokenizer.java:174) ~[ExamplePlugin-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.util.QuotedStringTokenizer$TokenizerState.next(QuotedStringTokenizer.java:168) ~[MineKeoFPS-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.util.QuotedStringTokenizer.parseEscape(QuotedStringTokenizer.java:142) ~[MineKeoFPS-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.util.QuotedStringTokenizer.parseUnquotedString(QuotedStringTokenizer.java:133) ~[MineKeoFPS-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.util.QuotedStringTokenizer.nextArg(QuotedStringTokenizer.java:97) ~[MineKeoFPS-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.util.QuotedStringTokenizer.parse(QuotedStringTokenizer.java:66) ~[MineKeoFPS-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.command.ArgumentStack.parse(ArgumentStack.java:113) ~[MineKeoFPS-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.bukkit.brigadier.PaperCommodore$UnknownCommandListener.onUnknownCommand(PaperCommodore.java:74) ~[MineKeoFPS-1.0-SNAPSHOT-all.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor50.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-292]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-292]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-292]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:374) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2208) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2168) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-292]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
[11:41:15 ERROR]: Could not pass event UnknownCommandEvent to AnotherPlugin v1.0
revxrsal.commands.exception.ArgumentParseException: Buffer overrun while parsing args
	at revxrsal.commands.util.QuotedStringTokenizer$TokenizerState.createException(QuotedStringTokenizer.java:174) ~[AnotherPlugin-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.util.QuotedStringTokenizer$TokenizerState.next(QuotedStringTokenizer.java:168) ~[Cosmetics-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.util.QuotedStringTokenizer.parseEscape(QuotedStringTokenizer.java:142) ~[Cosmetics-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.util.QuotedStringTokenizer.parseUnquotedString(QuotedStringTokenizer.java:133) ~[Cosmetics-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.util.QuotedStringTokenizer.nextArg(QuotedStringTokenizer.java:97) ~[Cosmetics-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.util.QuotedStringTokenizer.parse(QuotedStringTokenizer.java:66) ~[Cosmetics-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.command.ArgumentStack.parse(ArgumentStack.java:113) ~[Cosmetics-1.0-SNAPSHOT-all.jar:?]
	at revxrsal.commands.bukkit.brigadier.PaperCommodore$UnknownCommandListener.onUnknownCommand(PaperCommodore.java:74) ~[Cosmetics-1.0-SNAPSHOT-all.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor52.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-292]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-292]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-292]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:374) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2208) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2168) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-292]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-292]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]

```

Both ExamplePlugin and AnotherPlugin use Lamp. They both error.

**Comment by Revxrsal** [comment]
Thanks for the report. This has been fixed in https://github.com/Revxrsal/Lamp/commit/0ba32d9979db08dc588200d46e3add8451e92f8d.

**Comment by JasperTheMinecraftDev** [comment]
Awesome, thanks
